services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  web:
    build: .
    working_dir: /app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONPATH=/app/src
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./:/app
    ports:
      - "9999:9999"
    command: >
      sh -c "gunicorn -w 4 -b 0.0.0.0:9999 src.app:flask_app"
    depends_on:
      - redis

  celery:
    build: .
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./:/app
    command: celery -A src.make_celery worker --loglevel=info --uid=nobody --gid=nogroup
    depends_on:
      - redis
      - web
