# Enable everything
lint.select = ["ALL"]

# Line length to match specified requirement
line-length = 127

# Target Python 3.10
target-version = "py310"

# Common files to exclude
exclude = [
    ".git",
    ".env",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
]

lint.ignore = [
    "S101"
]

# Allow fix for all rules
lint.fixable = ["ALL"]
lint.unfixable = []

[lint.mccabe]
max-complexity = 25

[lint.pydocstyle]
convention = "pep257"  # PEP 8 style docstrings

[lint.pylint]
max-args = 8
max-locals = 15
max-statements = 100

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true
known-first-party = []
known-third-party = []